backend:
  name: github
  repo: minkfranc-spec/emmanuel-site

media_folder: "images"
public_folder: "/images"

collections:
  - name: "messages"
    label: "Mes Messages"
    folder: "/"
    extension: "json"
    format: "json"
    create: true
    fields:
      - {label: "Titre", name: "titre", widget: "string"}
      - {label: "Texte", name: "texte", widget: "text"}
